# Generated by Django 3.2.5 on 2021-07-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Openness', models.PositiveSmallIntegerField()),
                ('Neuroticism', models.PositiveSmallIntegerField()),
                ('Conscientiousness', models.PositiveSmallIntegerField()),
                ('Agreeableness', models.PositiveSmallIntegerField()),
                ('Extraversion', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
