# Generated by Django 3.2.4 on 2021-09-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0010_form_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
