# Generated by Django 3.2.4 on 2021-09-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0011_form_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Agreeableness',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=4),
        ),
        migrations.AlterField(
            model_name='form',
            name='Conscientiousness',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=4),
        ),
        migrations.AlterField(
            model_name='form',
            name='Extraversion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=4),
        ),
        migrations.AlterField(
            model_name='form',
            name='Neuroticism',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=4),
        ),
        migrations.AlterField(
            model_name='form',
            name='Openness',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=4),
        ),
    ]
